apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-authorization-server
  labels:
    app: identity-authorization-server
spec:
  selector:
    matchLabels:
      app: identity-authorization-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: identity-authorization-server
    spec:
      containers:
        - name: identity-authorization-server
          image: 'identity-authorization-server:v1'
          ports:
            - containerPort: 9000
              name: ingress-port
            - containerPort: 8081
              name: actuator-port
          env:
            - name: POSTGRES_HOST
              value: 'identity-authorization-db'
            - name: POSTGRES_DB
              value: "identity-authorization-db"
            - name: POSTGRES_USER
              value: "db_user"
            - name: POSTGRES_PASSWORD
              value: "should_be_from_secret"
            - name: USER_MANAGEMENT_SERVICE
              value: "http://user-management-service"
            - name: AUTH_SERVICE_ISSUER_URI
              value: "http://accounts.chat-socket.io"
            - name: JAVA_OPTS
              value: "-Xmx256m -Xms128m -Xss256k -XX:CompressedClassSpaceSize=32m -XX:-TieredCompilation"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - identity-authorization-server
                topologyKey: kubernetes.io/chat-microservices
