apiVersion: v1
kind: Service
metadata:
    name: identity-authorization-server
spec:
    ports:
        -
            port: 80
            targetPort: 8080
    selector:
        app: identity-authorization-server
